# B1.2 Kinetic Energy in Rotational Dynamics
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

# B1.2.1 Motivation
Rotational motion is governed not only by torque and angular momentum but also by **kinetic energy**. This lesson explores how to compute and interpret the kinetic energy of rotating rigid bodies using the **moment of inertia tensor** and angular velocity.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.2 Learning Objectives

By the end of this lesson, you should be able to:

- Write the general expression for rotational kinetic energy.
- Interpret the scalar and tensor forms of kinetic energy.
- Derive kinetic energy using point masses and the inertia tensor.
- Express kinetic energy in terms of $ \boldsymbol{\omega} \cdot \mathbf{L} $.
- Apply the formulas to simple and asymmetric rigid bodies.
- Use Python to compute rotational kinetic energy for a system of point masses.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.3 Conceptual Foundation

### Total Kinetic Energy

For a rigid body undergoing **pure rotation** (no translation), the total kinetic energy is the sum of the kinetic energy of all mass elements:

$$
T = \frac{1}{2} \sum_i m_i v_i^2
$$

Since each point moves in a circle about the axis of rotation, its velocity is related to the angular velocity $ \vec{\omega} $ by:

$$
\vec{v}_i = \vec{\omega} \times \vec{r}_i
$$

So,

$$
T = \frac{1}{2} \sum_i m_i \left\| \vec{\omega} \times \vec{r}_i \right\|^2
$$

This leads to a more compact and general form:

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.4 Tensor Form of Kinetic Energy

$$
T = \frac{1}{2} \vec{\omega}^T \mathbf{I} \vec{\omega}
$$

Where:

- $ \vec{\omega} $ is the angular velocity vector  
- $ \mathbf{I} $ is the **inertia tensor**
- $ \vec{\omega}^T $ is the transpose of $ \vec{\omega} $

### Alternative Form: $ \boldsymbol{\omega} \cdot \mathbf{L} $

We define angular momentum as:

$$
\vec{L} = \mathbf{I} \vec{\omega}
$$

Then kinetic energy becomes:

$$
T = \frac{1}{2} \vec{\omega} \cdot \vec{L}
$$

This form is particularly useful when $ \vec{L} $ is known (e.g., conserved) but the moment of inertia is complex or variable.

---

### Special Case: Principal Axes

If rotation is about a **principal axis**, the inertia tensor is diagonal, and the angular velocity aligns with one of the axes. Then:

$$
T = \frac{1}{2} I_1 \omega_1^2 + \frac{1}{2} I_2 \omega_2^2 + \frac{1}{2} I_3 \omega_3^2
$$

Only the component(s) of $ \vec{\omega} $ along the rotation axis contribute.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.5 Derivation

Given:

$$
\vec{v}_i = \vec{\omega} \times \vec{r}_i
\Rightarrow
\| \vec{v}_i \|^2 = (\vec{\omega} \times \vec{r}_i) \cdot (\vec{\omega} \times \vec{r}_i)
$$

Using the identity:

$$
\| \vec{\omega} \times \vec{r}_i \|^2 = \omega^2 r_i^2 - (\vec{\omega} \cdot \vec{r}_i)^2
$$

Substitute into the total kinetic energy:

$$
T = \frac{1}{2} \sum m_i (\omega^2 r_i^2 - (\vec{\omega} \cdot \vec{r}_i)^2)
$$

This expands into the inertia tensor form:

$$
T = \frac{1}{2} \vec{\omega}^T \mathbf{I} \vec{\omega}
$$

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.6 Example: Diagonal Tensor with Principal Axes

Suppose a body rotates about the $ z $-axis with angular velocity $ \vec{\omega} = (0, 0, \omega) $, and the inertia tensor is diagonal:

$$
\mathbf{I} =
\begin{bmatrix}
I_{xx} & 0 & 0 \\
0 & I_{yy} & 0 \\
0 & 0 & I_{zz}
\end{bmatrix}
$$

Then the kinetic energy becomes:

$$
T = \frac{1}{2} I_{zz} \omega^2
$$

This is the classic scalar formula you know from simpler systems.


### Python Example: Point Masses

Let's compute kinetic energy for a rotating set of point masses:

In [1]:
import numpy as np

def compute_inertia_tensor(masses, positions):
    I = np.zeros((3, 3))
    for m, r in zip(masses, positions):
        r = np.array(r)
        I += m * (np.dot(r, r) * np.eye(3) - np.outer(r, r))
    return I

def rotational_kinetic_energy(I, omega):
    return 0.5 * np.dot(omega, I @ omega)

# Masses and positions (e.g. cube corners)
masses = [1, 1, 1, 1]
positions = [
    [1, 1, 1],
    [-1, -1, 1],
    [-1, 1, -1],
    [1, -1, -1]
]

# Angular velocity vector (e.g. about z-axis)
omega = np.array([0, 0, 2])

# Compute inertia tensor and kinetic energy
I = compute_inertia_tensor(masses, positions)
T = rotational_kinetic_energy(I, omega)

print("Inertia Tensor:\n", I)
print("Rotational Kinetic Energy:", T)

Inertia Tensor:
 [[8. 0. 0.]
 [0. 8. 0.]
 [0. 0. 8.]]
Rotational Kinetic Energy: 16.0


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.2.7 Summary

| Quantity                  | Expression                                        |
|---------------------------|---------------------------------------------------|
| Translational KE          |  $ T = \frac{1}{2} M v^2 $                        |
| Rotational KE (scalar)    |  $ T = \frac{1}{2} I \omega^2 $                  |
| Rotational KE (tensor)    |  $ T = \frac{1}{2} \vec{\omega}^T \mathbf{I} \vec{\omega} $ |
| Rotational KE (alt. form) |  $ T = \frac{1}{2} \vec{\omega} \cdot \vec{L} $  |
| Principal axis rotation   |  $ T = \frac{1}{2} \sum I_i \omega_i^2 $         |

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<div class="alert alert-warning">

**Box 1**
    
A uniform thin rod of length $ L $ and mass $ M $ rotates about one end perpendicular to its length at angular speed $ \omega $. Find the rotational kinetic energy.

</div>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<div class="alert alert-warning">
    
**Box 2**
    
A rigid body has an inertia tensor:

$$
\mathbf{I} =
\begin{bmatrix}
3 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

and an angular velocity $ \vec{\omega} = [1, 2, 3] $. Compute:

1. $ \vec{L} = \mathbf{I} \vec{\omega} $  
2. $ T = \frac{1}{2} \vec{\omega} \cdot \vec{L} $


</div>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<div class="alert alert-warning">

**Box 3**
    
Explain why the kinetic energy is minimized when the angular velocity vector $ \vec{\omega} $ aligns with a principal axis, for a given angular momentum vector $ \vec{L} $.


</div>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## Detailed Solutions to Boxes
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

### Box 1: Rotating Rod

The moment of inertia of a uniform rod about one end is:

$$
I = \frac{1}{3} M L^2
$$

The angular speed is $ \omega $, so the kinetic energy is:

$$
T = \frac{1}{2} I \omega^2 = \frac{1}{2} \left( \frac{1}{3} M L^2 \right) \omega^2
= \frac{1}{6} M L^2 \omega^2
$$

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

### Box 2: Tensor Form

**Solution Part 1**: Angular momentum

$$
\vec{L} = \mathbf{I} \vec{\omega} =
\begin{bmatrix}
3 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
=
\begin{bmatrix}
3 \cdot 1 \\
2 \cdot 2 \\
1 \cdot 3
\end{bmatrix}
=
\begin{bmatrix}
3 \\
4 \\
3
\end{bmatrix}
$$

---

**Solution Part 2**: Kinetic energy

$$
T = \frac{1}{2} \vec{\omega} \cdot \vec{L} =
\frac{1}{2}
\left(1 \cdot 3 + 2 \cdot 4 + 3 \cdot 3\right)
=
\frac{1}{2}(3 + 8 + 9) = \frac{1}{2}(20) = 10
$$

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

### Box 3: Energy Minimization and Principal Axes

Given:
- $ \vec{L} = \mathbf{I} \vec{\omega} $
- $ T = \frac{1}{2} \vec{\omega} \cdot \vec{L} $

Let’s suppose we keep $ \vec{L} $ constant and vary $ \vec{\omega} $. This corresponds to seeking the orientation of $ \vec{\omega} $ that minimizes $ T $ under the constraint $ \vec{L} = \text{constant} $.

We interpret $ T $ as:

$$
T = \frac{1}{2} \vec{\omega}^T \mathbf{I} \vec{\omega}
$$

Subject to:

$$
\vec{L} = \mathbf{I} \vec{\omega} \Rightarrow \vec{\omega} = \mathbf{I}^{-1} \vec{L}
$$

Substituting:

$$
T = \frac{1}{2} \vec{L}^T \mathbf{I}^{-1} \vec{L}
$$

So for fixed $ \vec{L} $, the **kinetic energy is minimized when $ \mathbf{I}^{-1} $ is smallest in the direction of $ \vec{L} $** — that is, when $ \vec{L} $ lies along the eigenvector of $ \mathbf{I} $ with the **largest eigenvalue** (smallest inverse).

But for a given $ \vec{L} $, the **smallest $ T $** occurs when $ \vec{\omega} $ is **parallel to** $ \vec{L} $, which only happens when $ \vec{\omega} $ is aligned with a **principal axis**, since only then is $ \mathbf{I} \vec{\omega} = \lambda \vec{\omega} $.

**Conclusion**:
The kinetic energy is minimized for a given angular momentum when the body rotates about a **principal axis**.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">
