# B1.1 Principal Axes in Rotational Dynamics
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.1 Motivation
When analyzing the rotational motion of a rigid body, the distribution of mass relative to the rotation axis plays a critical role. For general 3D motion, this becomes mathematically complex. However, the concept of principal axes provides a powerful simplification — they are special axes about which the body can rotate without any tendency to wobble or change direction of angular velocity. Understanding principal axes is essential for topics such as gyroscopic motion, satellite attitude control, and moment of inertia tensor applications.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.2 Learning Objectives

By the end of this lesson, you should be able to:

- Define and interpret the concept of principal axes.
- Explain how principal axes relate to the moment of inertia tensor.
- Identify principal axes for common symmetrical objects.
- Diagonalize the inertia tensor to find principal moments and axes.
- Use Python to compute and visualize principal axes and moments.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.3 Conceptual Foundations

### What Are Principal Axes?

A **principal axis** of a rigid body is a direction about which the body can freely rotate without its angular velocity vector changing direction. For such an axis, the torque-free rotation is purely about that axis, and there is no **precession** or **nutation**.

Mathematically, they are the **eigenvectors** of the **inertia tensor** $ \mathbf{I} $, and the corresponding **eigenvalues** are called **principal moments of inertia**.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.4 The Inertia Tensor

We saw in Phase B that for a rigid body, the moment of inertia is generalized from a scalar to a **second-rank tensor**:

$$
\mathbf{I} =
\begin{bmatrix}
I_{xx} & -I_{xy} & -I_{xz} \\
-I_{yx} & I_{yy} & -I_{yz} \\
-I_{zx} & -I_{zy} & I_{zz}
\end{bmatrix}
$$

Where the diagonal terms are **moments of inertia** about the coordinate axes, and the off-diagonal terms are **products of inertia**. Specifically, we calculated the terms from:

$$
I_{ij} = \int_V \rho(\vec{r}) \left( \delta_{ij} \|\vec{r}\|^2 - r_i r_j \right) dV
$$

The inertia tensor depends on the **mass distribution** and the **choice of coordinate system**.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.5 Finding Principal Axes

### Step 1: Construct the Inertia Tensor

Given a mass distribution $ \rho(\mathbf{r}) $, integrate or sum over all mass elements to compute all components of $ \mathbf{I} $.

### Step 2: Solve the Eigenvalue Problem

To find the principal axes:

$$
\mathbf{I} \cdot \vec{v} = \lambda \vec{v}
$$

Where:

- $ \lambda $: principal moment of inertia  
- $ \vec{v} $: principal axis (eigenvector)

This is a **symmetric tensor**, so it always has **real eigenvalues** and **orthogonal eigenvectors**.

### Step 3: Change of Basis

Diagonalize the inertia tensor using a rotation matrix $ \mathbf{R} $ formed from the normalized eigenvectors:

$$
\mathbf{I}' = \mathbf{R}^{-1} \mathbf{I} \mathbf{R}
$$

The diagonalized matrix $ \mathbf{I}' $ represents the principal moments of inertia.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

### Example: Cube Corner Masses

Let’s take a simple case of four point masses located at corners of a cube:

In [6]:
import numpy as np

# Computes inertia tensor for a set of point masses.
def compute_inertia_tensor(masses, positions):
    I = np.zeros((3, 3))
    for m, r in zip(masses, positions):
        r = np.array(r)
        I += m * (np.dot(r, r) * np.eye(3) - np.outer(r, r))
    return I

# Returns eigenvalues (moments) and eigenvectors (axes) of inertia tensor.
def principal_axes(I):
    moments, axes = np.linalg.eigh(I)
    return moments, axes

# main code

# Cube corner configuration
masses = [1, 1, 1, 1]
positions = [
    [1, 1, 1],
    [-1, -1, 1],
    [-1, 1, -1],
    [1, -1, -1]
]

I = compute_inertia_tensor(masses, positions)
moments, axes = principal_axes(I)

print("Inertia Tensor:\n", I)
print("\nPrincipal Moments:\n", moments)
print("\nPrincipal Axes (columns):\n", axes)

Inertia Tensor:
 [[8. 0. 0.]
 [0. 8. 0.]
 [0. 0. 8.]]

Principal Moments:
 [8. 8. 8.]

Principal Axes (columns):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.6 Physical Interpretation

* **Principal axes** correspond to directions in which the angular momentum vector $\vec{L}$ is aligned with the angular velocity $\vec{\omega}$.

* Rotation about a **non-principal axis** leads to complex motion involving **precession and nutation**.

* For **symmetric bodies**, the axes of symmetry are principal axes.

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

## B1.1.6 Summary Table

| **Concept**              | **Description**                                                                 |
|--------------------------|---------------------------------------------------------------------------------|
| Principal Axis           | Axis about which pure rotation occurs with fixed angular velocity direction    |
| Inertia Tensor           | Second-rank tensor encoding mass distribution and shape                        |
| Principal Moments        | Eigenvalues of the inertia tensor; measure resistance to rotation about axes   |
| Diagonalization          | Process of rotating coordinates to align with principal axes                   |
| Eigenvectors             | Directions (axes) that diagonalize the inertia tensor                          |
| Symmetric Object         | Body whose geometric symmetry implies easily identified principal axes         |
| Products of Inertia      | Off-diagonal elements of the inertia tensor; vanish when using principal axes  |
| Stability of Rotation    | Rotation about a principal axis tends to be dynamically stable                 |

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<div class="alert alert-warning">

**Box 1**
    
Asymmetric Body — Inertia Tensor Diagonalization

Consider a rigid body with the following inertia tensor (in kg·m²) expressed in some coordinate system:

$$
\mathbf{I} =
\begin{bmatrix}
4 & 1 & 0 \\
1 & 3 & 0 \\
0 & 0 & 2
\end{bmatrix}
$$

1. Find the principal moments of inertia and principal axes.  
2. Explain the physical interpretation of the result.
</div>

<hr style="height:2px;border-width:0;color:gray;background-color:gray">

**Box 1 Solution**

We solve the eigenvalue problem:

$$
\det(\mathbf{I} - \lambda \mathbf{I}_3) = 0
$$

where $\mathbf{I}_3$ is the $3\times 3$ identity matrix.

The characteristic polynomial is:

$$
\begin{vmatrix}
4 - \lambda & 1 & 0 \\
1 & 3 - \lambda & 0 \\
0 & 0 & 2 - \lambda
\end{vmatrix}
= (2 - \lambda) \cdot \begin{vmatrix}
4 - \lambda & 1 \\
1 & 3 - \lambda
\end{vmatrix}
$$

Solving the $ 2 \times 2 $ determinant:

$$
(4 - \lambda)(3 - \lambda) - 1 = \lambda^2 - 7\lambda + 11
$$

So the characteristic equation becomes:

$$
(2 - \lambda)(\lambda^2 - 7\lambda + 11) = 0
$$

The eigenvalues (principal moments of inertia) are:

$$
\lambda_1 = 2, \quad
\lambda_{2,3} = \frac{7 \pm \sqrt{49 - 44}}{2} = \frac{7 \pm \sqrt{5}}{2}
$$

Which numerically gives:

- $ \lambda_1 = 2 $
- $ \lambda_2 \approx 2.38 $
- $ \lambda_3 \approx 4.62 $

Use numerical methods to find the eigenvectors of $ \mathbf{I} $:

In [5]:
import numpy as np

I = np.array([
    [4, 1, 0],
    [1, 3, 0],
    [0, 0, 2]
])

# Diagonalize
eigenvalues, eigenvectors = np.linalg.eigh(I)

print("Principal Moments of Inertia:", eigenvalues)
print("Principal Axes (columns are unit vectors):\n", eigenvectors)

Principal Moments of Inertia: [2.         2.38196601 4.61803399]
Principal Axes (columns are unit vectors):
 [[ 0.          0.52573111 -0.85065081]
 [ 0.         -0.85065081 -0.52573111]
 [ 1.          0.         -0.        ]]


So the third axis (z-direction) is already a principal axis (due to block-diagonal structure), and the other two axes are rotated in the xy-plane.

**Physical Interpretation**

* The body does not rotate symmetrically about all axes.

* There is no geometric symmetry that aligns the coordinate axes with all principal axes.

* The third axis (z) is already decoupled, and the other two axes are not orthogonal to coordinate axes but lie in a rotated xy-plane.

* Rotation about any principal axis results in pure, stable rotation.
<hr style="height:2px;border-width:0;color:gray;background-color:gray">